package routers

import (
	"arsip/handlers"
	"github.com/gofiber/fiber/v2"
)

func SetupRoutes(app *fiber.App) {

	app.Static("/", "./public")
	app.Get("/", handlers.Home)
	app.Get("/flush", handlers.FlushCache)
	app.Get("/design", handlers.Design)
	app.Get("/login", handlers.Login)
	app.Get("/print", handlers.PrintToPdf)
	rekap := app.Group("/rekap")
	rekap.Get("/rencana-satker",  handlers.RekapRencanaSatker)
	rekap.Get("/realisasi-satker",  handlers.RekapRealisasiSatker)
	rekap.Get("/rekap-paket-ppk",  handlers.RekapPaketPPK)

	register := app.Group("/register")
	register.Get("/", handlers.Register)
	register.Post("/", handlers.SubmitRegister)
	register.Get("/success", handlers.RegisterKonfirmasi)

	bukutamu := app.Group("/bukutamu")
	bukutamu.Get("/success", handlers.BukutamuKonfirmasi)
	bukutamu.Get("/list", handlers.LoggedMiddleware, handlers.BukuTamuList)
	bukutamu.Get("/data", handlers.LoggedMiddleware, handlers.GetJsonBukuTamu)
	bukutamu.Get("/:id", handlers.LoggedMiddleware, handlers.BukuTamuView)
	bukutamu.Get("/", handlers.BukuTamu)
	bukutamu.Post("/:id/update", handlers.BukuTamuUpdate)
	bukutamu.Post("/:id/proses", handlers.SubmitProsesBukuTamu)
	bukutamu.Post("/", handlers.SubmitBukuTamu)

	inbox := app.Group("/inbox", handlers.LoggedMiddleware)
	inbox.Get("/data", handlers.GetJsonInbox)
	inbox.Get("/:id", handlers.GetInbox)
	inbox.Get("/", handlers.GetAllInbox)

	feedback := app.Group("/feedback")
	feedback.Get("/success", handlers.FeedbackKonfirmasi)
	feedback.Get("/data", handlers.LoggedMiddleware, handlers.GetJsonFeedback)
	feedback.Get("/list", handlers.LoggedMiddleware, handlers.FeedbackList)
	feedback.Get("/kategori", handlers.LoggedMiddleware, handlers.FeedbackKategoriList)
	feedback.Post("/kategori", handlers.LoggedMiddleware, handlers.SubmitFeedbackKategori)
	feedback.Get("/kategori/delete/:id", handlers.LoggedMiddleware, handlers.DeleteFeedbackKategori)
	feedback.Get("/delete/:id", handlers.LoggedMiddleware, handlers.DeleteFeedback)
	feedback.Get("/:id", handlers.LoggedMiddleware, handlers.FeedbackView)
	feedback.Get("/", handlers.Feedback)
	feedback.Post("/", handlers.SubmitFeedback)


	app.Post("/login", handlers.SubmitLogin)
	app.Get("/download/:id", handlers.Download)
	app.Get("/download-all/:id", handlers.DownloadAll)
	app.Get("/logout", handlers.LoggedMiddleware, handlers.Logout)
	app.Get("/home", handlers.LoggedMiddleware, handlers.Home)
	app.Get("/profile", handlers.LoggedMiddleware, handlers.Profile)
	app.Get("/template-sk", handlers.GetTemplateSK)
	app.Get("/template-sk-pokja", handlers.GetTemplateSKPokja)
	templates := app.Group("/templates", handlers.LoggedMiddleware)
	templates.Get("/data", handlers.GetJsonTemplates)
	templates.Get("/edit", handlers.EditTemplates)
	templates.Get("/preview/:id", handlers.PreviewTemplates)
	templates.Get("/edit/:id", handlers.EditTemplates)
	templates.Post("/edit/:id", handlers.UpdateTemplates)
	templates.Get("/hapus/:id", handlers.DeleteTemplates)
	templates.Get("/", handlers.GetAllTemplates)
	templates.Get("/:id", handlers.GetTemplates)
	templates.Post("/", handlers.CreateTemplates)

	agency := app.Group("/agency", handlers.LoggedMiddleware)
	agency.Get("/data", handlers.GetJsonAgency)
	agency.Get("/edit", handlers.EditAgency)
	agency.Get("/edit/:id", handlers.EditAgency)
	agency.Post("/edit/:id", handlers.UpdateAgency)
	agency.Get("/hapus/:id", handlers.DeleteAgency)
	agency.Get("/", handlers.GetAllAgency)
	agency.Get("/:id", handlers.GetAgency)
	agency.Post("/", handlers.CreateAgency)

	ukbpj := app.Group("/ukpbj", handlers.LoggedMiddleware)
	ukbpj.Get("/data", handlers.GetJsonUkpbj)
	ukbpj.Get("/edit", handlers.EditUkpbj)
	ukbpj.Get("/edit/:id", handlers.EditUkpbj)
	ukbpj.Post("/edit/:id", handlers.UpdateUkpbj)
	ukbpj.Get("/hapus/:id", handlers.DeleteUkpbj)
	ukbpj.Get("/", handlers.GetAllUkpbj)
	ukbpj.Get("/:id", handlers.GetUkpbj)
	ukbpj.Post("/", handlers.CreateUkpbj)

	pegawai := app.Group("/pegawai", handlers.LoggedMiddleware)
	pegawai.Get("/data", handlers.GetJsonPegawai)
	pegawai.Get("/edit", handlers.EditPegawai)
	pegawai.Post("/edit/:id", handlers.UpdatePegawai)
	pegawai.Get("/edit/:id", handlers.EditPegawai)
	pegawai.Get("/hapus/:id", handlers.DeletePegawai)
	pegawai.Get("/", handlers.GetAllPegawai)
	pegawai.Get("/:id", handlers.GetPegawai)
	pegawai.Post("/", handlers.CreatePegawai)

	perubahanData := app.Group("/perubahan-data", handlers.LoggedMiddleware)
	perubahanData.Get("/data", handlers.GetJsonPerubahanData)
	perubahanData.Get("/edit", handlers.EditPerubahanData)
	perubahanData.Post("/edit/:id", handlers.UpdatePerubahanData)
	perubahanData.Get("/edit/:id", handlers.EditPerubahanData)
	perubahanData.Get("/hapus/:id", handlers.DeletePerubahanData)
	perubahanData.Get("/", handlers.GetAllPerubahanData)
	perubahanData.Get("/:id", handlers.GetPerubahanData)
	perubahanData.Post("/", handlers.CreatePerubahanData)

	document := app.Group("/document", handlers.LoggedMiddleware)
	document.Get("/data", handlers.GetJsonDocument)
	document.Get("/", handlers.GetAllDocument)
	document.Get("/:id", handlers.GetDocument)
	// document.Post("/", handlers.CreateDocument)
	// document.Put("/:id", handlers.UpdateDocument)
	document.Delete("/:id", handlers.DeleteDocument)

	verifikasi := app.Group("/verifikasi", handlers.LoggedMiddleware)
	verifikasi.Get("/data", handlers.GetJsonVerifikasi)
	verifikasi.Get("/view", handlers.GetVerifikasiView)
	verifikasi.Get("/", handlers.GetAllVerifikasi)
	verifikasi.Get("/:id", handlers.GetVerifikasi)
	verifikasi.Post("/:id", handlers.CreateVerifikasi)

	doctemplate := app.Group("/doc-template", handlers.LoggedMiddleware)
	doctemplate.Get("/data", handlers.GetJsonDocTemplate)
	doctemplate.Get("/edit", handlers.EditDocTemplate)
	doctemplate.Get("/edit/:id", handlers.EditDocTemplate)
	doctemplate.Post("/:id", handlers.UpdateDocTemplate)
	doctemplate.Get("/", handlers.GetAllDocTemplate)
	doctemplate.Get("/:id", handlers.GetDocTemplate)
	doctemplate.Post("/", handlers.CreateDocTemplate)
	doctemplate.Get("/hapus/:id", handlers.DeleteDocTemplate)

	checklist := app.Group("/checklist", handlers.LoggedMiddleware)
	checklist.Get("/data", handlers.GetJsonChecklist)
	checklist.Get("/edit", handlers.EditChecklist)
	checklist.Get("/edit/:id", handlers.EditChecklist)
	checklist.Get("/hapus/:id", handlers.DeleteChecklist)
	checklist.Get("/", handlers.GetAllChecklist)
	checklist.Get("/:id", handlers.GetChecklist)
	checklist.Post("/", handlers.CreateChecklist)

	panitia := app.Group("/pokja", handlers.LoggedMiddleware)
	panitia.Get("/data", handlers.GetJsonPanitia)
	panitia.Get("/edit", handlers.EditPanitia)
	panitia.Get("/edit/:id", handlers.EditPanitia)
	panitia.Get("/hapus/:id", handlers.DeletePanitia)
	panitia.Post("/:id", handlers.UpdatePanitia)
	panitia.Get("/", handlers.GetAllPanitia)
	panitia.Get("/:id", handlers.GetPanitia)
	panitia.Post("/", handlers.CreatePanitia)

	pp := app.Group("/pp", handlers.LoggedMiddleware)
	pp.Get("/data", handlers.GetJsonPp)
	pp.Get("/edit", handlers.EditPp)
	pp.Get("/edit/:id", handlers.EditPp)
	pp.Get("/hapus/:id", handlers.DeletePp)
	pp.Post("/:id", handlers.UpdatePp)
	pp.Get("/", handlers.GetAllPp)
	pp.Get("/:id", handlers.GetPp)
	pp.Post("/", handlers.CreatePp)

	reviu := app.Group("/reviu", handlers.LoggedMiddleware)
	reviu.Get("/data", handlers.GetJsonReviu)
	reviu.Get("/edit", handlers.EditReviu)
	reviu.Get("/edit/:id", handlers.EditReviu)
	reviu.Get("/hapus/:id", handlers.DeleteReviu)
	reviu.Post("/:id", handlers.UpdateReviu)
	reviu.Get("/", handlers.GetAllReviu)
	reviu.Get("/:id", handlers.GetReviu)
	reviu.Post("/", handlers.CreateReviu)

	paket := app.Group("/paket", handlers.LoggedMiddleware)
	paket.Post("/create", handlers.CreatePaket)
	paket.Get("/data", handlers.GetJsonPaket)
	paket.Get("/edit", handlers.EditPaket)
	paket.Get("/edit/:id", handlers.EditPaket)
	paket.Post("/approve/:id", handlers.ApprovePaket)
	paket.Post("/send-ukpbj/:id", handlers.KirimPaketUkpbj)
	paket.Post("/send-pokja/:id", handlers.KirimPaketPokja)
	paket.Post("/ganti-ppk/:id", handlers.GantiPPK)
	paket.Post("/send-pp/:id", handlers.KirimPaketPp)
	paket.Get("/dok-pendukung/:id/download", handlers.DownloadPendukung)
	paket.Post("/dok-pendukung/:id", handlers.SimpanDokPendukungPengadaan)
	paket.Post("/hps/:id", handlers.UpdateHpsPaket)
	paket.Post("/checklist/:id", handlers.SimpanPersyaratanPaket)
	paket.Post("/save/:id", handlers.SavePPk)
	paket.Get("/hapus/:id", handlers.DeletePaket)
	paket.Get("/dok-paket/:id/hapus", handlers.HapusDokPaket)
	paket.Get("/pilih-pokja/:id", handlers.PilihPokjaPaket)
	paket.Get("/pilih-pp/:id", handlers.PilihPPPaket)
	paket.Get("/pilih-ppk/:id", handlers.PilihPPPaket)
	paket.Get("/surat-penunjukan/:id", handlers.SuratPenunjukan)
	paket.Post("/:id", handlers.UpdatePaket)
	paket.Get("/", handlers.GetAllPaket)
	paket.Get("/:id", handlers.GetPaket)

	dokfinal := app.Group("/dok-final", handlers.LoggedMiddleware)
	dokfinal.Post("/:id", handlers.SimpanDokumenPersiapanPaket)
	dokfinal.Post("/:id/persetujuan", handlers.SimpanDokumenPersiapanPaketPersetujuan)
	dokfinal.Get("/:id/persetujuan", handlers.DokPersiapanPaketPersetujuan)
	dokfinal.Get("/:id", handlers.DokPersiapanPaket)

	pengadaan := app.Group("/pengadaan", handlers.LoggedMiddleware)
	pengadaan.Post("/simpan-kode/:id", handlers.SimpanKodeTender)
	pengadaan.Get("/:id", handlers.PengadaanPaket)

	hasil := app.Group("/hasil", handlers.LoggedMiddleware)
	hasil.Post("/:id/upload", handlers.SimpanDokHasilPengadaan)
	hasil.Post("/:id", handlers.SimpanHasilPengadanPaket)
	hasil.Get("/:id/download", handlers.DownloadHasilPengadaan)
	hasil.Get("/:id", handlers.HasilPengadanPaket)

	satker :=  app.Group("/satker", handlers.LoggedMiddleware)
	satker.Get("/json", handlers.GetJsonSatker)

	sirup := app.Group("/rencana", handlers.LoggedMiddleware)
	sirup.Get("/json", handlers.GetJsonPaketSirup)
	sirup.Get("/swakelola-json", handlers.GetJsonSwakelolaSirup)
	sirup.Get("/:id", handlers.GetPaketSirup)
	sirup.Get("/swakelola/:id", handlers.GetSwakelolaSirup)

	kajiulang := app.Group("/kajiulang", handlers.LoggedMiddleware)
	kajiulang.Post("/publish/:id", handlers.PublishKajiUlang)
	kajiulang.Post("/penjelasan/:id", handlers.JawabKajiUlang)
	kajiulang.Get("/penjelasan/:id", handlers.GetJawabKajiUlang)
	kajiulang.Get("/data/:id", handlers.GetJsonKajiUlang)
	kajiulang.Get("/list/:id", handlers.GetKajiUlangList)
	kajiulang.Get("/berita-acara/:id", handlers.PreviewBA)
	kajiulang.Get("/:id", handlers.GetKajiUlang)

	beritacara := app.Group("/berita-acara", handlers.LoggedMiddleware)
	beritacara.Get("/nego/:id", handlers.GetJsonKajiUlang)
	beritacara.Get("/penetapan/:id", handlers.GetKajiUlangList)

	cetak := app.Group("/preview")//, handlers.LoggedMiddleware)
	cetak.Get("/image/:id", handlers.PreviewImage)
	cetak.Get("/templates/:id", handlers.PreviewImage)
	cetak.Get("/sk-pp/:id", handlers.PreviewSkPp)
	cetak.Get("/sk-pp/:id/print", handlers.CetakSkPp)
	cetak.Get("/sk-pokja/:id", handlers.PreviewSkPokja)
	cetak.Get("/sk-pokja/:id/print", handlers.CetakSkPokja)
	cetak.Get("/ba-kajiulang/:id", handlers.PreviewBAKajiUlang)
	cetak.Get("/ba-kajiulang/:id/print", handlers.CetakBAKajiUlang)
	cetak.Get("/ba-nego/:id", handlers.PreviewBANego)
	cetak.Get("/ba-nego/:id/print", handlers.CetakBANego)
	cetak.Get("/ba-penetapan/:id", handlers.PreviewBAPenetapan)
	cetak.Get("/ba-penetapan/:id/print", handlers.CetakBAPenetapan)

	kontrak := app.Group("/kontrak", handlers.LoggedMiddleware)
	kontrak.Post("/:id", handlers.SimpanKontrakPaket)
	kontrak.Post("/:id/upload", handlers.SimpanDokKontrak)
	kontrak.Get("/:id/download", handlers.DownloadKontrak)
	kontrak.Get("/:id", handlers.KontrakPaket)

	pekerjaan := app.Group("/hasil-pekerjaan", handlers.LoggedMiddleware)
	pekerjaan.Post("/:id", handlers.SimpanHasilPekerjaan)
	pekerjaan.Post("/:id/upload", handlers.SimpanDokHasilPekerjaan)
	pekerjaan.Get("/:id/download", handlers.DownloadPekerjaan)
	pekerjaan.Get("/:id", handlers.HasilPekerjaan)

	home := app.Group("/dashboard")
	home.Get("/json-progress-rup", handlers.GetJsonProgressRup)
	home.Get("/json-paket-prioritas", handlers.GetJsonPaketPrioritas)
	home.Get("/json-rekap-satker", handlers.GetJsonRekapSatker)
	home.Get("/json-beban-personel", handlers.GetJsonBebanPersonel)
	home.Get("/json-rekap-paket-per-satker", handlers.GetJsonRekapPaketPerSatker)
	home.Get("/json-rekap-paket-ppk", handlers.GetJsonRekapPaketPPK)

	itkp := app.Group("/itkp")
	itkp.Get("/", handlers.Itkp)
	itkp.Get("/rup", handlers.GetJsonItkpRup)
	itkp.Get("/rup/detil", handlers.GetItkpRupDetail)
	itkp.Get("/pemilihan", handlers.GetJsonItkpPemilihan)
	itkp.Get("/pemilihan/detil", handlers.GetItkpPemilihanDetil)
	itkp.Get("/tender", handlers.GetJsonItkpTender)
	itkp.Get("/tender/detil", handlers.GetItkpTenderDetil)
	itkp.Get("/purchase", handlers.GetJsonItkpPurchase)
	itkp.Get("/purchase/detil", handlers.GetItkpPurchaseDetil)
	itkp.Get("/nontender", handlers.GetJsonItkpNonTender)
	itkp.Get("/nontender/detil", handlers.GetItkpNonTenderDetil)
	itkp.Get("/rekap", handlers.GetJsonItkpLokal)
	// 404 Handler
	app.Use(func(c *fiber.Ctx) error {
		return c.Status(fiber.StatusNotFound).Render("errors/error-404", fiber.Map{}) // => 404 "Not Found"
	})
}
